[theme]
base = "light"
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
[theme]
base = "dark" # Set dark as the default
# You might want different colors for dark mode
primaryColor = "#7792E3" # Example: A lighter blue for dark mode
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor="#FAFAFA"
font="sans serif"